
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[477] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  103,  101,    1,    1,   95,   95,  101,  101,
      101,  102,  102,   25,  102,  102,  102,  102,   35,  102,
      102,  102,   17,  102,  102,  102,  102,   30,  102,  102,
      102,  102,  102,  102,  102,  102,  102,    1,    1,   95,
       95,    0,    0,    1,   95,    0,    0,    0,    0,    0,
        0,    0,   18,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   25,    0,
        0,    0,    0,    0,    0,    0,   35,    0,    0,    0,
        0,   17,    0,    0,    0,    0,    0,    0,    0,   30,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   96,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   18,   71,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   73,    0,    0,    0,    0,
       45,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       69,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   98,    0,   97,    0,   26,   72,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   74,    0,    0,   46,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   70,    0,    0,
        0,    0,   43,    0,    0,   65,    0,   61,   63,   75,
        0,    0,   47,   49,   51,   53,    0,    0,   10,   57,
        0,   59,    0,    0,    0,    0,    0,   93,   89,    0,
       91,   77,   55,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   97,    0,
        0,    0,    0,   66,    0,   62,   64,   76,    0,    0,
       48,   50,   52,   54,    0,    0,   58,   60,    0,    0,
        0,    0,    0,   94,   90,    0,   92,   78,   56,    0,

       44,    0,    0,   67,    0,    0,   32,    0,    0,   10,
        0,    0,    0,   83,   85,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   98,    0,   99,
        0,    0,    0,   68,    0,    0,    0,    0,    0,    0,
        0,   84,   86,    0,    0,    6,    0,    0,    0,    0,
       32,    4,    2,    0,  100,    0,    0,   27,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,
       12,    0,    0,    7,    0,    0,    0,    0,   36,    5,
        3,    0,    0,    0,    0,    0,    0,    0,    0,   81,
        0,   27,    8,    0,   19,    0,   20,    0,   23,    0,

       24,    0,    0,    0,   33,    0,   34,    0,   11,   12,
        0,    0,    0,    0,    0,    0,    0,   82,    0,   31,
        9,    0,   41,    0,   37,   79,   19,   20,   23,   24,
        0,   21,    0,   22,   33,   34,    0,    0,    0,   13,
        0,   14,    0,    0,    0,   42,    0,   38,   80,   87,
        0,   21,   22,    0,   15,    0,   16,   13,   14,    0,
       28,    0,   29,   88,    0,    0,   15,   16,   28,   29,
        0,    0,    0,   39,   40,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,    1,
        1,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   18,   18,   18,   18,   18,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   18,   18,   39,   40,   41,   42,   43,
       18,   44,   45,   46,   47,   48,   49,   18,   50,   51,
       52,   53,   54,   55,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   18,   18,   66,   67,   68,
       69,   70,   18,   71,   72,   73,   74,   75,   76,   18,
       77,   78,   79,    1,   80,   81,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[82] =
    {   0,
        1,    2,    2,    3,    4,    5,    3,    4,    4,    4,
        6,    4,    4,    4,    4,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    7,    3,    7,    4,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    4,    4,
        4
    } ;

static yyconst flex_uint16_t yy_base[503] =
    {   0,
        0,   10,    2,    3,    5,   14,   19,   57,   20,   27,
       95,  133, 1179, 1180,  114,   77,  142,  152,   83,  176,
     1169, 1180,  122, 1180,    1,    3,    4,  105, 1180,   17,
      175, 1150, 1180,   28,   19,   27,  147, 1180,   59,  250,
      254,  281,  285,  103,  312,  316, 1167,  343,  347,  356,
      360, 1171, 1165,  137,  375,  387,  161,  377, 1169, 1163,
      167,  386, 1167,  157,  236,  403,   63,  229,  392,  164,
      129,  135,  137, 1143,  424,  442,  235,  463, 1180,  154,
      187,  234,  242,  240,  256,  328, 1180,  273,  291,  497,
     1142, 1180,  322,  323,  330,  334,  375,  375,  435, 1180,

      368,  383,  535,  549,  576,  580,  477,  607,  611, 1159,
      638,  642,  669,  654,  671, 1163, 1157,  683,  321,  696,
     1150,  388, 1137,  447,  462,  676,  443,  479,  670, 1136,
      446,  446, 1135,  482,  688,  481, 1157, 1180,  470,  733,
      498,  502, 1133,  517, 1132, 1131, 1130,  530,  526, 1129,
     1128, 1127, 1126,  541,  532, 1180,  539, 1125,  550, 1124,
     1180,  567,  556,  686,  575, 1123, 1122,  582, 1121, 1120,
     1180, 1119,  594,  616,  641,  669,  676, 1119,  667,  686,
     1139,  760,  764, 1127, 1135,  695, 1180, 1180,  695,  708,
      730, 1109,  724, 1108, 1105, 1102,  737,  735, 1101, 1098,

     1095, 1094,  747,  740, 1180, 1091, 1088, 1180,  751,  738,
      752,  755, 1087, 1084,  744, 1081, 1080, 1180, 1077,  743,
      810, 1074, 1180,  748,  750, 1180, 1073, 1180, 1180, 1180,
      769,  751, 1180, 1180, 1180, 1180,  769,  766, 1093, 1180,
      776, 1180,  772,  773, 1067, 1066,  779, 1180, 1180,  780,
     1180, 1180, 1180, 1064, 1001,  791,  998,  789,   10,  793,
      797,  845,  861,  831,  877,  893, 1013,  994, 1016,  990,
      784,  794,  805, 1180,  988, 1180, 1180, 1180,  852,  810,
     1180, 1180, 1180, 1180,  867,  867, 1180, 1180,  868,  867,
      987,  982,  871, 1180, 1180,  873, 1180, 1180, 1180,  981,

     1180,  875,  880, 1180,  885,  872, 1003,  979,  978,  998,
      927,  880,  881, 1180, 1180,  889,  890,   11,   46,  906,
      177,  879,  925,  919,  903,  884,  954, 1180,  867, 1180,
      866,  897,  904, 1180,  914,  901,  864,  863,  850,  908,
      907, 1180, 1180,  919,  926, 1180,  919,  919,  923,  933,
      871, 1180, 1180,  847, 1180,  841,  932,  858,  827,  838,
      828,  752,  746,  257,  741,  727,  707,  717,  701,  691,
      679,  322,  642, 1180,  928,  929,  933,  943, 1180, 1180,
     1180,  635,  947,  634,  633,  943,  627,  939,  624, 1180,
      622,  633, 1180,  625,  626,  614,  616,  613,  614,  578,

      584,  581,  547,  551,  531,  522,  528,  324,  522,  521,
      512,  484,  387,  945,  467,  943,  451, 1180,  450, 1180,
     1180,  446, 1180,  953, 1180, 1180,  457,  436,  418,  405,
      400,  400,  391,  392,  382,  372,  368,  343,  328,  301,
      293,  288,  267,  250,  205, 1180,  954, 1180, 1180, 1180,
      954,  226,  225,  191,  183,  164,  169,  168,  160,  147,
      123,  114,  111, 1180,  956,  958,  110,  108,  100,   69,
      960,   26,    7, 1180, 1180, 1180, 1028, 1035, 1042, 1048,
     1052, 1057, 1062, 1067, 1074, 1081, 1086, 1089, 1093, 1096,
     1100, 1103, 1107, 1110, 1114, 1117, 1121, 1124, 1128, 1131,

     1135, 1138
    } ;

static yyconst flex_int16_t yy_def[503] =
    {   0,
      477,  477,  478,  478,  478,  478,  478,  478,  478,  478,
      479,  479,  476,  476,  480,  476,  480,  480,  481,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  482,
      482,  482,  482,  483,  482,  482,  476,  480,  480,  480,
      480,  476,  476,  476,  480,  480,  481,  481,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  482,  482,  482,  482,  483,  482,  482,  476,
      482,  482,  482,  483,  483,  476,  476,  482,  476,  481,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  484,  482,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  484,  484,  483,  484,  484,  476,  476,  476,  485,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      486,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  487,  488,  476,  476,  484,  476,  485,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  486,  476,  476,  476,  476,  476,  489,
      490,  491,  492,  476,  493,  494,  476,  487,  476,  488,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  489,  476,  490,  476,  491,  476,  492,

      476,  495,  496,  493,  476,  494,  476,  476,  476,  476,
      497,  498,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      495,  476,  496,  476,  476,  476,  499,  500,  497,  476,
      498,  476,  501,  502,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  499,  476,  500,  476,  476,  476,  501,
      476,  502,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,    0,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476
    } ;

static yyconst flex_uint16_t yy_nxt[1262] =
    {   0,
       14,   15,   16,   15,   17,   23,   23,  476,   28,   19,
       14,   15,   16,   15,   17,  323,  360,   28,  476,   19,
      324,  361,   31,   37,   20,  476,   14,   21,   24,   24,
       37,   29,   84,  475,   20,   32,   14,   21,   25,   25,
       29,   85,   26,   26,   83,   33,   38,   27,   27,   30,
       39,  362,  474,   38,   89,   34,  363,   39,   30,   84,
       31,   96,   97,   35,   98,   25,   25,   36,   85,   26,
       26,   83,  470,   32,   27,   27,   30,   39,   54,   54,
       54,   89,   34,   33,   39,   30,   51,   57,   96,   97,
       35,   98,   59,   34,   36,   22,   40,   41,   40,   42,

      102,   35,  147,  469,   44,   36,  106,  114,   86,   45,
       60,  468,  116,  467,  470,   48,   49,   48,   50,   46,
       34,   46,   47,   52,  463,   78,  469,  102,   35,  147,
      117,   87,   36,   22,   40,   41,   40,   42,   54,   54,
       54,   53,   44,   55,   56,   55,   50,   45,   79,   88,
       99,   52,  461,   55,   56,   55,   50,   46,   80,   46,
       47,   52,   81,  459,  476,   57,  158,   82,  159,   53,
       59,  458,  468,  100,  457,  160,   88,  101,   90,   53,
       61,  121,  365,  138,  120,   80,  467,  366,   60,   81,
      156,   91,   62,  158,   82,  159,  455,   83,  139,  122,

      140,   92,  160,  157,  101,   63,   64,   65,   66,   67,
       68,   93,   69,   70,   71,   72,   84,   73,   74,   94,
       75,   76,   77,   95,   83,  139,  122,  140,  453,  452,
      157,  464,   63,   64,   65,   66,   67,   68,   93,   69,
       70,   71,   72,   84,   73,   74,   94,   75,   76,   77,
       95,  103,  104,  103,  105,  103,  111,  103,  105,  107,
      463,  171,  402,  107,  108,  141,  148,  403,  108,  142,
      149,   85,  461,  172,  109,  173,  109,  110,  109,  174,
      109,  110,  112,  113,  112,  105,  112,  113,  112,  105,
      107,  459,  141,  148,  107,  108,  142,  149,   85,  108,

      172,  175,  173,  442,  458,  109,  174,  109,  110,  109,
       89,  109,  110,  112,  113,  112,  105,  112,  119,  112,
      105,  107,  119,  119,  119,  107,  118,  411,  175,  437,
      108,   86,  412,  440,  438,  184,  109,   89,  109,  110,
      109,  176,  109,  110,   48,   49,   48,   50,   48,   49,
       48,   50,   52,  457,   87,   96,   52,   55,   56,   55,
       50,   55,   56,   55,   50,   52,   97,   98,  176,   52,
       53,  177,   88,  455,   53,  436,   55,   56,   55,   50,
      476,   57,   96,   53,   52,  435,   59,   53,   55,   56,
       55,   50,  443,   97,   98,  453,   52,  444,  177,   88,

      120,  434,   53,  452,   60,  432,  178,  179,  430,  102,
      150,  151,  152,  153,   53,  123,  124,  125,  126,  127,
      128,  429,  129,  130,  131,  154,  180,  132,  133,  186,
      134,  135,  136,  178,  179,  143,  102,  155,   99,  428,
      144,  145,  123,  124,  125,  126,  127,  128,  146,  129,
      130,  131,  154,  180,  132,  133,  186,  134,  135,  136,
      427,  100,  143,  162,  155,  101,   78,  144,  145,  163,
      164,  165,  450,  188,  166,  146,  449,  448,  167,  168,
      106,  114,  196,  206,  207,  169,  116,  170,  189,   79,
      162,  190,  101,  446,  442,  191,  163,  164,  165,   80,

       90,  166,  220,   81,  117,  167,  168,  218,   82,  196,
      206,  207,  169,   91,  170,  189,  197,  440,  190,  219,
      198,  209,  191,   92,  410,  409,   80,  210,  211,  220,
       81,  436,  407,   93,  435,   82,  103,  104,  103,  105,
      224,   94,  225,  197,  107,   95,  219,  198,  209,  108,
      103,  104,  103,  105,  210,  211,  405,  434,  107,  109,
       93,  109,  110,  108,  227,  231,  232,  224,   94,  225,
      237,  238,   95,  109,  239,  109,  110,  112,  113,  112,
      105,  112,  113,  112,  105,  107,  432,  430,  401,  107,
      108,  227,  231,  232,  108,  241,  243,  237,  238,  244,

      109,  239,  109,  110,  109,  247,  109,  110,  112,  113,
      112,  105,  112,  119,  112,  105,  107,  429,  399,  428,
      107,  118,  241,  243,  397,  108,  244,  250,  254,  427,
      395,  109,  247,  109,  110,  109,  392,  109,  110,  103,
      111,  103,  105,  112,  113,  112,  105,  107,  426,  255,
      425,  107,  108,  423,  250,  254,  108,  476,  114,  421,
      420,  418,  109,  116,  109,  110,  109,  413,  109,  110,
      112,  113,  112,  105,  476,  114,  255,  182,  181,  256,
      116,  117,  410,  108,  112,  113,  112,  105,  199,  200,
      201,  202,  107,  476,  182,  476,  110,  118,  117,  476,

       57,  371,  257,  203,  409,   59,  256,  109,  192,  183,
      110,  258,  260,  193,  194,  204,  245,  212,  261,  120,
      213,  195,  369,   60,  214,  215,  270,  271,  246,  257,
      203,  216,  408,  217,  221,  192,  221,  407,  258,  260,
      193,  194,  204,  245,  212,  261,  405,  213,  195,  222,
      272,  214,  215,  270,  271,  246,  401,  399,  216,  223,
      217,  112,  119,  112,  262,  112,  119,  112,  105,  264,
      273,  275,  279,  107,  265,  280,  285,  272,  108,  286,
      289,  290,  291,  266,  109,  293,  109,  267,  109,  296,
      109,  110,  300,  302,  292,  303,  307,  273,  275,  279,

      305,  308,  280,  285,  309,  311,  286,  289,  290,  291,
      312,  221,  293,  221,  313,  306,  296,  316,  317,  300,
      302,  292,  303,  307,  320,  322,  222,  305,  308,  325,
      326,  309,  311,  331,  263,  114,  223,  312,  397,  332,
      116,  313,  306,  395,  316,  317,  112,  113,  112,  262,
      333,  320,  322,  393,  264,  337,  325,  326,  117,  265,
      331,  392,  112,  113,  112,  262,  332,  390,  266,  109,
      264,  109,  267,  355,  351,  265,  381,  333,  112,  113,
      112,  262,  337,  335,  266,  109,  264,  109,  267,  380,
      379,  327,  374,  330,  112,  113,  112,  262,  336,  338,

      266,  109,  264,  109,  267,  339,  340,  265,  341,  344,
      335,  345,  347,  348,  349,  350,  266,  109,  356,  109,
      267,  357,  358,  359,  367,  336,  338,  373,  372,  371,
      369,  364,  339,  340,  375,  341,  344,  376,  345,  347,
      348,  349,  350,  377,  378,  356,  382,  383,  357,  358,
      359,  367,  384,  355,  373,  112,  113,  112,  262,  385,
      386,  375,  387,  264,  376,  388,  389,  391,  327,  414,
      377,  378,  415,  382,  383,  416,  417,  266,  109,  384,
      183,  267,  419,  422,  424,  445,  385,  386,  447,  387,
      451,  465,  388,  389,  391,  466,  414,  471,  472,  415,

      473,  310,  416,  417,  353,  352,  351,  346,  343,  419,
      422,  424,  445,  342,  334,  447,  330,  451,  465,  269,
      328,  263,  466,  321,  471,  472,  319,  473,   18,   18,
       18,   18,   18,   18,   18,   22,   22,   22,   22,   22,
       22,   22,   43,   43,   43,   43,   43,   43,   43,   51,
       51,   51,   51,   51,   58,   58,   58,   58,  106,  106,
      106,  106,  106,  106,  115,  115,  115,  115,  263,  263,
      263,  263,  263,  263,  329,  329,  329,  329,  329,  329,
      329,  354,  354,  354,  354,  354,  354,  354,  368,  318,
      368,  370,  315,  314,  370,  394,  310,  394,  396,  304,

      301,  396,  398,  299,  398,  400,  298,  297,  400,  404,
      295,  404,  406,  294,  288,  406,  431,  287,  431,  433,
      284,  283,  433,  439,  282,  439,  441,  281,  278,  441,
      454,  277,  454,  456,  276,  274,  456,  460,  269,  460,
      462,  268,  106,  462,  259,  253,  252,  251,  249,  248,
      242,  240,  236,  235,  234,  233,  230,  229,  228,  226,
      137,  208,  205,  187,  185,  115,  115,  106,   92,  161,
      137,   58,   58,   51,   51,  106,   92,   51,  476,   13,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476
    } ;

static yyconst flex_int16_t yy_chk[1262] =
    {   0,
        1,    1,    1,    1,    1,    3,    4,    0,    5,    1,
        2,    2,    2,    2,    2,  259,  318,    6,    0,    2,
      259,  318,    7,    9,    1,    0,    1,    1,    3,    4,
       10,    5,   26,  473,    2,    7,    2,    2,    3,    4,
        6,   27,    3,    4,   25,    7,    9,    3,    4,    5,
        9,  319,  472,   10,   30,    7,  319,   10,    6,   26,
        8,   34,   35,    7,   36,    3,    4,    7,   27,    3,
        4,   25,  470,    8,    3,    4,    5,    9,   16,   16,
       16,   30,    7,    8,   10,    6,   19,   19,   34,   35,
        7,   36,   19,    8,    7,   11,   11,   11,   11,   11,

       39,    8,   67,  469,   11,    8,   44,   44,   28,   11,
       19,  468,   44,  467,  463,   15,   15,   15,   15,   11,
        8,   11,   11,   15,  462,   23,  461,   39,    8,   67,
       44,   28,    8,   12,   12,   12,   12,   12,   54,   54,
       54,   15,   12,   17,   17,   17,   17,   12,   23,   28,
       37,   17,  460,   18,   18,   18,   18,   12,   23,   12,
       12,   18,   23,  459,   57,   57,   71,   23,   72,   17,
       57,  458,  457,   37,  456,   73,   28,   37,   31,   18,
       20,   61,  321,   64,   57,   23,  455,  321,   57,   23,
       70,   31,   20,   71,   23,   72,  454,   80,   64,   61,

       64,   31,   73,   70,   37,   20,   20,   20,   20,   20,
       20,   31,   20,   20,   20,   20,   81,   20,   20,   31,
       20,   20,   20,   31,   80,   64,   61,   64,  453,  452,
       70,  445,   20,   20,   20,   20,   20,   20,   31,   20,
       20,   20,   20,   81,   20,   20,   31,   20,   20,   20,
       31,   40,   40,   40,   40,   41,   41,   41,   41,   40,
      444,   77,  364,   41,   40,   65,   68,  364,   41,   65,
       68,   82,  443,   77,   40,   83,   40,   40,   41,   84,
       41,   41,   42,   42,   42,   42,   43,   43,   43,   43,
       42,  442,   65,   68,   43,   42,   65,   68,   82,   43,

       77,   85,   83,  441,  440,   42,   84,   42,   42,   43,
       88,   43,   43,   45,   45,   45,   45,   46,   46,   46,
       46,   45,  119,  119,  119,   46,   45,  372,   85,  408,
       46,   86,  372,  439,  408,  119,   45,   88,   45,   45,
       46,   89,   46,   46,   48,   48,   48,   48,   49,   49,
       49,   49,   48,  438,   86,   93,   49,   50,   50,   50,
       50,   51,   51,   51,   51,   50,   94,   95,   89,   51,
       48,   96,   86,  437,   49,  436,   55,   55,   55,   55,
       58,   58,   93,   50,   55,  435,   58,   51,   56,   56,
       56,   56,  413,   94,   95,  434,   56,  413,   96,   86,

       58,  433,   55,  432,   58,  431,   97,   98,  430,  101,
       69,   69,   69,   69,   56,   62,   62,   62,   62,   62,
       62,  429,   62,   62,   62,   69,  102,   62,   62,  122,
       62,   62,   62,   97,   98,   66,  101,   69,   99,  428,
       66,   66,   62,   62,   62,   62,   62,   62,   66,   62,
       62,   62,   69,  102,   62,   62,  122,   62,   62,   62,
      427,   99,   66,   75,   69,   99,   78,   66,   66,   75,
       75,   76,  422,  124,   76,   66,  419,  417,   76,   76,
      107,  107,  127,  131,  132,   76,  107,   76,  124,   78,
       75,  125,   99,  415,  412,  125,   75,   75,   76,   78,

       90,   76,  139,   78,  107,   76,   76,  136,   78,  127,
      131,  132,   76,   90,   76,  124,  128,  411,  125,  136,
      128,  134,  125,   90,  410,  409,   78,  134,  134,  139,
       78,  407,  406,   90,  405,   78,  103,  103,  103,  103,
      141,   90,  142,  128,  103,   90,  136,  128,  134,  103,
      104,  104,  104,  104,  134,  134,  404,  403,  104,  103,
       90,  103,  103,  104,  144,  148,  149,  141,   90,  142,
      154,  155,   90,  104,  157,  104,  104,  105,  105,  105,
      105,  106,  106,  106,  106,  105,  402,  401,  400,  106,
      105,  144,  148,  149,  106,  159,  162,  154,  155,  163,

      105,  157,  105,  105,  106,  165,  106,  106,  108,  108,
      108,  108,  109,  109,  109,  109,  108,  399,  398,  397,
      109,  108,  159,  162,  396,  109,  163,  168,  173,  395,
      394,  108,  165,  108,  108,  109,  392,  109,  109,  111,
      111,  111,  111,  112,  112,  112,  112,  111,  391,  174,
      389,  112,  111,  387,  168,  173,  112,  114,  114,  385,
      384,  382,  111,  114,  111,  111,  112,  373,  112,  112,
      113,  113,  113,  113,  115,  115,  174,  114,  113,  175,
      115,  114,  371,  113,  118,  118,  118,  118,  129,  129,
      129,  129,  118,  113,  115,  113,  113,  118,  115,  120,

      120,  370,  176,  129,  369,  120,  175,  118,  126,  118,
      118,  177,  179,  126,  126,  129,  164,  135,  180,  120,
      135,  126,  368,  120,  135,  135,  186,  189,  164,  176,
      129,  135,  367,  135,  140,  126,  140,  366,  177,  179,
      126,  126,  129,  164,  135,  180,  365,  135,  126,  140,
      190,  135,  135,  186,  189,  164,  363,  362,  135,  140,
      135,  182,  182,  182,  182,  183,  183,  183,  183,  182,
      191,  193,  197,  183,  182,  198,  203,  190,  183,  204,
      209,  210,  211,  182,  182,  212,  182,  182,  183,  215,
      183,  183,  220,  224,  211,  225,  232,  191,  193,  197,

      231,  237,  198,  203,  238,  241,  204,  209,  210,  211,
      243,  221,  212,  221,  244,  231,  215,  247,  250,  220,
      224,  211,  225,  232,  256,  258,  221,  231,  237,  260,
      261,  238,  241,  271,  264,  264,  221,  243,  361,  272,
      264,  244,  231,  360,  247,  250,  262,  262,  262,  262,
      273,  256,  258,  359,  262,  280,  260,  261,  264,  262,
      271,  358,  263,  263,  263,  263,  272,  356,  262,  262,
      263,  262,  262,  354,  351,  263,  339,  273,  265,  265,
      265,  265,  280,  279,  263,  263,  265,  263,  263,  338,
      337,  265,  331,  329,  266,  266,  266,  266,  279,  285,

      265,  265,  266,  265,  265,  286,  289,  266,  290,  293,
      279,  296,  302,  303,  305,  306,  266,  266,  312,  266,
      266,  313,  316,  317,  322,  279,  285,  326,  325,  324,
      323,  320,  286,  289,  332,  290,  293,  333,  296,  302,
      303,  305,  306,  335,  336,  312,  340,  341,  313,  316,
      317,  322,  344,  311,  326,  327,  327,  327,  327,  345,
      347,  332,  348,  327,  333,  349,  350,  357,  327,  375,
      335,  336,  376,  340,  341,  377,  378,  327,  327,  344,
      327,  327,  383,  386,  388,  414,  345,  347,  416,  348,
      424,  447,  349,  350,  357,  451,  375,  465,  466,  376,

      471,  310,  377,  378,  309,  308,  307,  300,  292,  383,
      386,  388,  414,  291,  275,  416,  270,  424,  447,  269,
      268,  267,  451,  257,  465,  466,  255,  471,  477,  477,
      477,  477,  477,  477,  477,  478,  478,  478,  478,  478,
      478,  478,  479,  479,  479,  479,  479,  479,  479,  480,
      480,  480,  480,  480,  481,  481,  481,  481,  482,  482,
      482,  482,  482,  482,  483,  483,  483,  483,  484,  484,
      484,  484,  484,  484,  485,  485,  485,  485,  485,  485,
      485,  486,  486,  486,  486,  486,  486,  486,  487,  254,
      487,  488,  246,  245,  488,  489,  239,  489,  490,  227,

      222,  490,  491,  219,  491,  492,  217,  216,  492,  493,
      214,  493,  494,  213,  207,  494,  495,  206,  495,  496,
      202,  201,  496,  497,  200,  497,  498,  199,  196,  498,
      499,  195,  499,  500,  194,  192,  500,  501,  185,  501,
      502,  184,  181,  502,  178,  172,  170,  169,  167,  166,
      160,  158,  153,  152,  151,  150,  147,  146,  145,  143,
      137,  133,  130,  123,  121,  117,  116,  110,   91,   74,
       63,   60,   59,   53,   52,   47,   32,   21,   13,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
/*                        --------------------------------------------------------------------
				                       	VIVEK SINGH 
						 	2019MCS2574	      		 					
                          --------------------------------------------------------------------
*/
#line 8 "lexer.l"

#include <stdio.h>
#include<string.h>
#include "parser.tab.h"






#line 926 "lex.yy.c"

#define INITIAL 0
#define a_tag 1
#define font_tag 2
#define img_tag 3
#define table_tag 4
#define comment 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 31 "lexer.l"




#line 1154 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 477 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1180 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 35 "lexer.l"
; //SPACES TABS AND NEWLINES IGNORED
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "lexer.l"
{
							//printf("HTML\n");
							return HTML;
							}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "lexer.l"
{
							//printf("HTMLE\n");
							return HTMLE;
							}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "lexer.l"
{
							//printf("HEAD\n");
							return HEAD;
							}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "lexer.l"
{
							//printf("HEADE\n");
							return HEADE;
							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "lexer.l"
{
							//printf("BODY\n");
							return BODY;
							}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "lexer.l"
{
							//printf("BODYE\n");
							return BODYE;
							}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "lexer.l"
{
							//printf("TITLE\n");
							return TITLE;
							}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "lexer.l"
{
							//printf("TITLEE\n");
							return TITLEE;
							}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "lexer.l"
{ 
											BEGIN img_tag;
											//printf("IMG\n");
											return IMG;
											}
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 85 "lexer.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGSRC;

											}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "lexer.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGSRC;
											}
	YY_BREAK


case 13:
YY_RULE_SETUP
#line 115 "lexer.l"
{
										
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGWIDTH;
											}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 128 "lexer.l"
{
										
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGWIDTH;
											}
	YY_BREAK


case 15:
YY_RULE_SETUP
#line 143 "lexer.l"
{
										
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGHEIGHT;
											}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 155 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGHEIGHT;
											}
	YY_BREAK

case 17:
YY_RULE_SETUP
#line 168 "lexer.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 173 "lexer.l"
{ 
											BEGIN a_tag;
											//printf("A\n");
											return A;
											}
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 182 "lexer.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return HREF;
											}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 195 "lexer.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return HREF;
											}
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 211 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return ATITLE;
											}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 223 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return ATITLE;
											}
	YY_BREAK


case 23:
YY_RULE_SETUP
#line 237 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return ANAME;
											}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 249 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return ANAME;
											}
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 264 "lexer.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 269 "lexer.l"
{
											//printf("AE\n");
											return AE;
											}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 274 "lexer.l"
{
											BEGIN table_tag;
											//printf("TABLE\n");
											return TABLE;
											}
	YY_BREAK

case 28:
YY_RULE_SETUP
#line 283 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											return BORDER;
											}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 294 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											return BORDER;
											}
	YY_BREAK

case 30:
YY_RULE_SETUP
#line 306 "lexer.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 310 "lexer.l"
{
											//printf("TABLEE\n");
											return TABLEE;	
											}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 315 "lexer.l"
{
											BEGIN font_tag;
											//printf("FONT\n");
											return FONT;
											}
	YY_BREAK

case 33:
YY_RULE_SETUP
#line 322 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											return SIZE;
											}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 332 "lexer.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											//printf("%s\n",link);
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(link);
											return SIZE;
											}
	YY_BREAK

case 35:
YY_RULE_SETUP
#line 345 "lexer.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 350 "lexer.l"
{
											//printf("FONTE\n");
											return FONTE;
											}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 355 "lexer.l"
{
							//printf("FIGURE\n");
							return FIGURE;	
							}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 360 "lexer.l"
{
							//printf("FIGUREE\n");
							return FIGUREE;	
							}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 365 "lexer.l"
{
							//printf("FIGCAPTION\n");
							return FIGCAPTION;	
							}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 370 "lexer.l"
{
							//printf("FIGCAPTIONE\n");
							return FIGCAPTIONE;	
							}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 375 "lexer.l"
{
							//printf("CENTER\n");
							return CENTER;	
							}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 380 "lexer.l"
{
							//printf("CENTERE\n");
							return CENTERE;	
							}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 385 "lexer.l"
{
							//printf("BR\n");
							return BR;	
							}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 389 "lexer.l"
{
							//printf("BR\n");
							return BR;	
							}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 394 "lexer.l"
{
							//printf("P\n");
							return P;	
							}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 399 "lexer.l"
{
							//printf("PE\n");
							return PE;	
							}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 404 "lexer.l"
{
							//printf("H1\n");
							return H1;	
							}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 409 "lexer.l"
{
							//printf("H1E\n");
							return H1E;	
							}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 414 "lexer.l"
{
							//printf("H2\n");
							return H2;	
							}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 419 "lexer.l"
{
							//printf("H2E\n");
							return H2E;	
							}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 424 "lexer.l"
{
							//printf("H3\n");
							return H3;	
							}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 429 "lexer.l"
{
							//printf("H3E\n");
							return H3E;	
							}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 434 "lexer.l"
{
							//printf("H4\n");
							return H4;	
							}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 439 "lexer.l"
{
							//printf("H4E\n");
							return H4E;	
							}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 444 "lexer.l"
{
							//printf("UL\n");
							return UL;	
							}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 449 "lexer.l"
{
							//printf("ULE\n");
							return ULE;	
							}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 454 "lexer.l"
{
							//printf("LI\n");
							return LI;	
							}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 459 "lexer.l"
{
							//printf("LIE\n");
							return LIE;	
							}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 464 "lexer.l"
{
							//printf("OL\n");
							return OL;	
							}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 469 "lexer.l"
{
							//printf("OLE\n");
							return OLE;	
							}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 474 "lexer.l"
{
							//printf("DL\n");
							return DL;	
							}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 479 "lexer.l"
{
							//printf("DLE\n");
							return DLE;	
							}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 484 "lexer.l"
{
							//printf("DT\n");
							return DT;	
							}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 489 "lexer.l"
{
							//printf("DTE\n");
							return DTE;	
							}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 494 "lexer.l"
{
							//printf("DD\n");
							return DD;	
							}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 499 "lexer.l"
{
							//printf("DDE\n");
							return DDE;	
							}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 504 "lexer.l"
{
							//printf("DIV\n");
							return DIV;	
							}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 509 "lexer.l"
{
							//printf("DIVE\n");
							return DIVE;	
							}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 514 "lexer.l"
{
							//printf("U\n");
							return U;	
							}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 519 "lexer.l"
{
							//printf("UE\n");
							return UE;	
							}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 524 "lexer.l"
{
							//printf("B\n");
							return B;	
							}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 529 "lexer.l"
{
							//printf("BE\n");
							return BE;	
							}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 534 "lexer.l"
{
							//printf("I\n");
							return I;	
							}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 539 "lexer.l"
{
							//printf("IE\n");
							return IE;	
							}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 544 "lexer.l"
{
							//printf("EM\n");
							return EM;	
							}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 549 "lexer.l"
{
							//printf("EME\n");
							return EME;	
							}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 554 "lexer.l"
{
							//printf("TT\n");
							return TT;	
							}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 559 "lexer.l"
{
							//printf("TTE\n");
							return TTE;	
							}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 564 "lexer.l"
{
							//printf("STRONG\n");
							return STRONG;	
							}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 569 "lexer.l"
{
							//printf("STRONGE\n");
							return STRONGE;	
							}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 574 "lexer.l"
{
							//printf("SMALL\n");
							return SMALL;	
							}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 579 "lexer.l"
{
							//printf("SMALLE\n");
							return SMALLE;	
							}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 584 "lexer.l"
{
							//printf("SUB\n");
							return SUB;	
							}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 589 "lexer.l"
{
							//printf("SUBE\n");
							return SUBE;	
							}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 594 "lexer.l"
{
							//printf("SUP\n");
							return SUP;	
							}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 599 "lexer.l"
{
							//printf("SUPE\n");
							return SUPE;	
							}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 605 "lexer.l"
{
							//printf("CAPTION\n");
							return CAPTION;	
							}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 610 "lexer.l"
{
							//printf("CAPTIONE\n");
							return CAPTIONE;	
							}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 615 "lexer.l"
{
							//printf("TH\n");
							return TH;	
							}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 620 "lexer.l"
{
							//printf("THE\n");
							return THE;	
							}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 625 "lexer.l"
{
							//printf("TR\n");
							return TR;	
							}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 630 "lexer.l"
{
							//printf("TRE\n");
							return TRE;	
							}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 635 "lexer.l"
{
							//printf("TD\n");
							return TD;	
							}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 640 "lexer.l"
{
							//printf("TDE\n");
							return TDE;	
							}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 645 "lexer.l"
{
							//printf("%s\n",yytext);
							yylval.s = (char *)malloc(sizeof(yytext));
							yylval.s = strdup(yytext);
							return TEXT;
							}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 652 "lexer.l"
{
							//printf("GREEK\n");
							yylval.s = (char *)malloc(sizeof(yytext));
							yylval.s = strdup(yytext);
							return GREEK;
							}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 659 "lexer.l"
{BEGIN comment;}
	YY_BREAK

case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 663 "lexer.l"
{ 
											char *ss=yytext;
											int len=strlen(ss);
											char sc[len+1];
											for(int i=0;i<=len-3;i++)
											sc[i]=ss[i];
											sc[len-3]='\0';
											////printf("COMMENT\n");
											yylval.s = (char *)malloc(sizeof(yytext));
											yylval.s = strdup(sc);
											BEGIN 0;
											return COMMENT;
											}
	YY_BREAK

case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 679 "lexer.l"
;
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 681 "lexer.l"
;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 683 "lexer.l"
{yylval.s = (char *)malloc(sizeof(yytext));
							yylval.s = strdup(yytext);
							return TEXT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 690 "lexer.l"
ECHO;
	YY_BREAK
#line 2163 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(a_tag):
case YY_STATE_EOF(font_tag):
case YY_STATE_EOF(img_tag):
case YY_STATE_EOF(table_tag):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 477 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 477 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 476);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 690 "lexer.l"




int yywrap(){
return 1;
}


