
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[424] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
      101,   98,    1,    1,   95,   95,   98,   98,   98,  100,
      100,   25,  100,  100,  100,  100,   35,  100,  100,  100,
      100,  100,  100,  100,   30,  100,    1,    1,   95,   95,
        0,    1,   95,    0,    0,    0,    0,    0,    0,    0,
       99,   18,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    0,
        0,    0,    0,    0,   35,    0,    0,    0,    0,    0,
        0,    0,   17,    0,    0,    0,    0,   30,    0,    0,
       96,    0,   97,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   18,   71,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   73,    0,    0,    0,
       45,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       69,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       26,   72,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   74,    0,
        0,   46,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   70,    0,    0,    0,    0,   43,    0,    0,   65,
        0,   61,   63,   75,    0,    0,   47,   49,   51,   53,

        0,    0,   10,   57,   59,    0,    0,    0,    0,    0,
       93,   89,    0,   91,   77,   55,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   66,    0,   62,
       64,   76,    0,    0,   48,   50,   52,   54,    0,    0,
       58,   60,    0,    0,    0,    0,    0,   94,   90,    0,
       92,   78,   56,    0,   44,    0,    0,   67,    0,    0,
       32,    0,    0,   10,    0,    0,   83,   85,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   68,    0,    0,    0,    0,    0,    0,    0,
       84,   86,    0,    0,    6,    0,    0,    0,    0,   32,

        4,    2,    0,    0,   27,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   11,    0,   12,    0,    0,
        7,    0,    0,    0,    0,   36,    5,    3,    0,    0,
        0,    0,    0,    0,    0,    0,   81,    0,   27,    8,
        0,   19,    0,   20,    0,   23,    0,   24,    0,    0,
        0,   33,    0,   34,    0,   11,   12,    0,    0,    0,
        0,    0,    0,    0,   82,    0,   31,    9,    0,   41,
        0,   37,   79,   19,   20,   23,   24,    0,   21,    0,
       22,   33,   34,    0,    0,    0,   13,    0,   14,    0,
        0,    0,   42,    0,   38,   80,   87,    0,   21,   22,

        0,   15,    0,   16,   13,   14,    0,   28,    0,   29,
       88,    0,    0,   15,   16,   28,   29,    0,    0,    0,
       39,   40,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,    1,
        1,    1,    1,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   16,   16,   16,   16,   16,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   16,   16,   37,   38,   39,   40,   41,
       16,   42,   43,   44,   45,   46,   47,   16,   48,   49,
        1,   50,    1,   51,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   16,   16,   62,   63,   64,
       65,   66,   16,   67,   68,   69,   70,   71,   72,   16,
       73,   74,   75,    1,   76,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[78] =
    {   0,
        1,    2,    2,    3,    4,    5,    6,    4,    4,    1,
        7,    4,    4,    6,    8,    6,    6,    6,    6,    6,
        6,    1,    1,    6,    1,    4,    4,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    4,
        4,    4,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    4,    4,    4
    } ;

static yyconst flex_uint16_t yy_base[445] =
    {   0,
        0,   77,   70,   87,   14,   28,    1,  102,    8,   13,
      918,  919,  173,   26,  249,    0,  320,  393,  908,  919,
      144,  919,    1,    3,    4,   68,  919,    5,  174,  891,
        2,    3,   28,   90,  919,   67,  121,  138,    0,    0,
      906,  155,    0,    0,  457,    0,  905,  888,   21,  507,
      919,  908,  125,  159,  170,   70,  175,  246,   72,   77,
       81,  886,  216,  550,  136,  270,  919,   79,  132,  132,
      139,  157,  158,  234,  919,  167,  156,  307,  885,  178,
      176,  183,  919,  186,  225,  236,  264,  919,  229,  229,
      919,  884,  919,  883,  247,  278,  312,  244,  296,  345,

      882,  247,  251,  881,  315,  592,  351,  901,  919,  260,
      378,  257,  281,  879,  312,  878,  877,  876,  332,  330,
      875,  874,  873,  872,  358,  349,  919,  356,  871,  870,
      919,  364,  364,  391,  381,  869,  868,  372,  867,  866,
      919,  865,  386,  395,  405,  411,  426,  865,  425,  440,
      919,  919,  441,  432,  435,  863,  429,  862,  861,  860,
      442,  438,  859,  858,  857,  856,  452,  448,  919,  855,
      854,  919,  459,  446,  462,  460,  853,  852,  446,  851,
      850,  919,  849,  444,  516,  848,  919,  460,  477,  919,
      847,  919,  919,  919,  500,  480,  919,  919,  919,  919,

      523,  520,  867,  919,  919,  521,  519,  845,  844,  529,
      919,  919,  534,  919,  919,  919,  844,  843,  542,  842,
      545,    8,  552,  556,  541,  546,  549,  919,  840,  919,
      919,  919,  571,  553,  919,  919,  919,  919,  569,  567,
      919,  919,  570,  568,  839,  838,  584,  919,  919,  587,
      919,  919,  919,  837,  919,  594,  599,  919,  607,  595,
      857,  832,  831,  849,  601,  600,  919,  919,  608,  610,
       43,   49,  826,   52,  599,  839,  833,  817,  602,  813,
      611,  618,  919,  623,  612,  808,  807,  804,  620,  619,
      919,  919,  634,  638,  919,  631,  631,  633,  645,  822,

      919,  919,  796,  644,  816,  792,  808,  798,  802,  794,
      393,  796,  786,  772,  787,  786,  774,  780,  394,  757,
      919,  640,  639,  643,  653,  919,  919,  919,  753,  652,
      748,  747,  648,  744,  644,  741,  919,  730,  748,  919,
      725,  726,  717,  723,  718,  719,  710,  716,  713,  705,
      708,  704,  598,  598,  516,  594,  591,  550,  542,  683,
      651,  501,  648,  500,  919,  498,  919,  919,  494,  919,
      657,  919,  919,  506,  502,  491,  489,  476,  452,  429,
      435,  405,  397,  349,  341,  345,  336,  327,  333,  315,
      308,  292,  919,  661,  919,  919,  919,  660,  300,  293,

      278,  277,  234,  237,  233,  229,  223,  180,  161,  162,
      919,  661,  665,  160,  159,  151,  116,  668,   91,   22,
      919,  919,  919,  732,  740,  747,  750,  756,  762,  768,
      774,  780,  786,  792,  798,  804,  810,  816,  822,  828,
      834,  840,  846,  852
    } ;

static yyconst flex_int16_t yy_def[445] =
    {   0,
      424,  424,  425,  425,  425,  425,  425,  425,  425,  425,
      423,  423,  426,  423,  426,   15,  427,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,   15,   15,   15,   15,
      423,  423,   15,   15,  427,   45,  423,  428,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  428,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  429,  430,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  431,  432,  433,  434,
      423,  435,  436,  423,  429,  423,  430,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      431,  423,  432,  423,  433,  423,  434,  423,  437,  438,
      435,  423,  436,  423,  423,  423,  423,  439,  440,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  437,  423,  438,
      423,  423,  423,  441,  442,  439,  423,  440,  423,  443,
      444,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      441,  423,  442,  423,  423,  423,  443,  423,  444,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,    0,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423
    } ;

static yyconst flex_uint16_t yy_nxt[997] =
    {   0,
       12,   13,   14,   13,   29,   12,   16,   16,   16,   17,
       12,   34,   16,  276,   12,   30,   34,   26,  277,  423,
       16,   12,   18,   16,   12,   19,   16,   42,   42,   42,
       72,   26,   35,   84,   49,   31,   36,   35,   27,   73,
       77,   36,   71,   32,   85,   51,  422,   33,  307,   16,
       16,   16,   27,  308,  309,   72,   28,  312,   84,  310,
       31,   36,  313,   86,   73,   77,   36,   71,   32,   85,
       28,   74,   33,   21,   16,   16,   16,   12,   13,   14,
       13,   28,   12,   16,   16,   16,   17,   12,   86,   16,
       21,   12,   75,   87,   22,   28,  127,   16,   12,   18,

       16,   12,   19,   16,   23,   29,   90,  118,   24,  128,
       76,   22,  129,   25,   88,  421,   30,  130,   89,  417,
       71,   23,   37,   38,   37,   24,   16,   16,   16,   23,
       25,   90,  118,   24,  128,   76,   31,  129,   25,   37,
       38,   37,  130,   89,   32,   71,   23,   66,   33,  109,
       24,   16,   16,   16,  416,   25,   42,   42,   42,   72,
      141,   31,  415,  414,  110,  417,  111,   73,   67,   32,
      143,  410,  142,   33,   37,   38,   37,   78,   68,   40,
       40,   40,   69,  416,   72,   40,  112,   70,   79,  110,
      113,  111,   73,   40,  144,  143,   40,  142,   41,   40,

      114,  145,   77,   68,  146,  115,  116,   69,   80,   84,
      119,  112,   70,  117,  120,  113,   81,   85,   86,  144,
       82,  147,   40,   40,   40,  114,  145,   77,  408,  146,
      115,  116,  406,   80,   84,  119,  405,   74,  117,  120,
      415,   81,   85,   86,  404,   82,  147,   40,   40,   40,
       43,   44,   43,  132,  148,   40,   40,   40,   75,  133,
      134,   40,  121,  122,  123,  124,  149,   87,   90,   40,
      150,  152,   40,   66,   41,   40,   76,  125,  132,  148,
      414,  160,  170,  402,  133,  134,  153,  171,   88,  126,
      184,  149,   89,   90,   67,  150,  400,  188,   40,   40,

       40,   76,  125,  399,   68,  154,  160,  170,   69,  155,
       78,  153,  171,   70,  126,  184,  411,   89,  410,  189,
      408,   79,  188,   40,   40,   40,   46,   46,   46,   68,
      154,  161,   46,   69,  155,  162,  406,  389,   70,  405,
       46,   80,  156,   46,  189,   47,   46,  157,  158,   81,
      387,  404,  173,   82,  402,  159,  161,  191,  174,  175,
      162,  163,  164,  165,  166,  195,   80,  156,  196,   46,
       46,   46,  157,  158,   81,  182,  167,  173,   82,  185,
      159,  185,  191,  174,  175,  201,  202,  183,  168,  203,
      195,  206,  186,  196,   46,   46,   46,   48,  349,  358,

      383,  167,  187,  350,  359,  207,   49,   50,  382,  210,
      201,  202,  183,  168,  203,  213,  206,   51,  217,  208,
       52,   53,   54,   55,   56,   57,  218,   58,   59,   60,
      207,  209,   61,   62,  210,   63,   64,   65,  400,  381,
      213,  219,  220,  217,  208,   52,   53,   54,   55,   56,
       57,  218,   58,   59,   60,  399,  209,   61,   62,  221,
       63,   64,   65,   46,   46,   46,  219,  220,  223,   46,
      224,  225,  226,  227,  229,  233,  234,   46,   91,  239,
       46,  379,   47,   46,  221,  240,  243,  244,  247,  250,
      245,  254,  377,  223,  376,  224,  225,  226,  227,  229,

      233,  234,  246,  256,  239,  375,   46,   46,   46,  374,
      240,  243,  244,  247,  250,  245,  254,  185,  397,  185,
      257,  384,  396,  261,  395,  393,  385,  246,  256,  259,
      186,   46,   46,   46,   94,   95,   96,   97,   98,   99,
      187,  100,  101,  102,  260,  257,  103,  104,  261,  105,
      106,  107,  389,  262,  259,  387,  263,  265,  266,   94,
       95,   96,   97,   98,   99,  269,  100,  101,  102,  260,
      270,  103,  104,  273,  105,  106,  107,  135,  262,  275,
      136,  263,  265,  266,  137,  138,  278,  279,  280,  281,
      269,  139,  282,  140,  357,  270,  286,  356,  273,  287,

      284,  383,  135,  288,  275,  136,  289,  290,  354,  137,
      138,  278,  279,  280,  281,  285,  139,  282,  140,  176,
      293,  286,  177,  294,  287,  284,  178,  179,  288,  296,
      297,  289,  290,  180,  298,  181,  299,  303,  304,  305,
      285,  306,  314,  320,  176,  293,  322,  177,  294,  323,
      324,  178,  179,  325,  296,  297,  329,  330,  180,  298,
      181,  299,  303,  304,  305,  331,  306,  314,  320,  332,
      333,  322,  334,  335,  323,  324,  336,  338,  325,  361,
      362,  329,  330,  363,  364,  366,  369,  371,  390,  392,
      331,  394,  398,  391,  332,  333,  412,  334,  335,  413,

      418,  336,  338,  419,  361,  362,  420,  382,  363,  364,
      366,  369,  371,  352,  392,  381,  394,  398,  379,  377,
      348,  412,  376,  346,  413,  418,  375,  344,  419,  374,
      342,  420,   15,   15,   15,   15,   15,   15,   15,   15,
       20,   20,   20,   20,   20,   20,   20,   20,   39,   39,
       39,  339,   39,   45,  373,   45,   92,   92,   92,   92,
       92,   92,   92,   92,  315,  372,  315,  315,  370,  315,
      317,  368,  367,  317,  317,  317,  341,  365,  341,  341,
      360,  341,  343,  357,  318,  343,  343,  343,  345,  356,
      345,  345,  316,  345,  347,  355,  354,  347,  347,  347,

      351,  352,  351,  351,  348,  351,  353,  346,  344,  353,
      353,  353,  378,  342,  378,  378,  340,  378,  380,  339,
      337,  380,  380,  380,  386,  300,  386,  386,  328,  386,
      388,  327,  326,  388,  388,  388,  401,  321,  401,  401,
      319,  401,  403,  318,  316,  403,  403,  403,  407,  311,
      407,  407,  264,  407,  409,  302,  301,  409,  409,  409,
      300,  295,  292,  291,  283,  274,  272,  271,  268,  267,
      264,  258,  255,  253,  252,  251,  249,  248,  242,  241,
      238,  237,  236,  235,  232,  231,  230,  228,  222,  216,
      215,  214,  212,  211,  205,  204,  200,  199,  198,  197,

      194,  193,  192,  190,  108,  172,  169,  151,   93,   83,
      131,  108,   93,   45,   39,   83,   39,  423,   11,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423

    } ;

static yyconst flex_int16_t yy_chk[997] =
    {   0,
        1,    1,    1,    1,    7,    1,    1,    1,    1,    1,
        1,    9,    1,  222,    1,    7,   10,    5,  222,    0,
        1,    1,    1,    1,    1,    1,    1,   14,   14,   14,
       24,    6,    9,   31,   49,    7,    9,   10,    5,   25,
       28,   10,   23,    7,   32,   49,  420,    7,  271,    1,
        1,    1,    6,  271,  272,   24,    5,  274,   31,  272,
        7,    9,  274,   33,   25,   28,   10,   23,    7,   32,
        6,   26,    7,    3,    1,    1,    1,    2,    2,    2,
        2,    5,    2,    2,    2,    2,    2,    2,   33,    2,
        4,    2,   26,   34,    3,    6,   59,    2,    2,    2,

        2,    2,    2,    2,    3,    8,   36,   56,    3,   59,
       26,    4,   60,    3,   34,  419,    8,   61,   34,  417,
       68,    4,   37,   37,   37,    4,    2,    2,    2,    3,
        4,   36,   56,    3,   59,   26,    8,   60,    3,   38,
       38,   38,   61,   34,    8,   68,    4,   21,    8,   53,
        4,    2,    2,    2,  416,    4,   42,   42,   42,   69,
       65,    8,  415,  414,   53,  410,   53,   70,   21,    8,
       71,  409,   65,    8,   13,   13,   13,   29,   21,   13,
       13,   13,   21,  408,   69,   13,   54,   21,   29,   53,
       54,   53,   70,   13,   72,   71,   13,   65,   13,   13,

       55,   73,   76,   21,   77,   55,   55,   21,   29,   80,
       57,   54,   21,   55,   57,   54,   29,   81,   82,   72,
       29,   84,   13,   13,   13,   55,   73,   76,  407,   77,
       55,   55,  406,   29,   80,   57,  405,   74,   55,   57,
      404,   29,   81,   82,  403,   29,   84,   13,   13,   13,
       15,   15,   15,   63,   85,   15,   15,   15,   74,   63,
       63,   15,   58,   58,   58,   58,   86,   87,   89,   15,
       90,   95,   15,   66,   15,   15,   74,   58,   63,   85,
      402,   98,  102,  401,   63,   63,   95,  103,   87,   58,
      110,   86,   87,   89,   66,   90,  400,  112,   15,   15,

       15,   74,   58,  399,   66,   96,   98,  102,   66,   96,
       78,   95,  103,   66,   58,  110,  392,   87,  391,  113,
      390,   78,  112,   15,   15,   15,   17,   17,   17,   66,
       96,   99,   17,   66,   96,   99,  389,  388,   66,  387,
       17,   78,   97,   17,  113,   17,   17,   97,   97,   78,
      386,  385,  105,   78,  384,   97,   99,  115,  105,  105,
       99,  100,  100,  100,  100,  119,   78,   97,  120,   17,
       17,   17,   97,   97,   78,  107,  100,  105,   78,  111,
       97,  111,  115,  105,  105,  125,  126,  107,  100,  128,
      119,  132,  111,  120,   17,   17,   17,   18,  311,  319,

      383,  100,  111,  311,  319,  133,   18,   18,  382,  135,
      125,  126,  107,  100,  128,  138,  132,   18,  143,  134,
       18,   18,   18,   18,   18,   18,  144,   18,   18,   18,
      133,  134,   18,   18,  135,   18,   18,   18,  381,  380,
      138,  145,  146,  143,  134,   18,   18,   18,   18,   18,
       18,  144,   18,   18,   18,  379,  134,   18,   18,  147,
       18,   18,   18,   45,   45,   45,  145,  146,  149,   45,
      150,  153,  154,  155,  157,  161,  162,   45,   45,  167,
       45,  378,   45,   45,  147,  168,  173,  174,  176,  179,
      175,  184,  377,  149,  376,  150,  153,  154,  155,  157,

      161,  162,  175,  188,  167,  375,   45,   45,   45,  374,
      168,  173,  174,  176,  179,  175,  184,  185,  369,  185,
      189,  355,  366,  196,  364,  362,  355,  175,  188,  195,
      185,   45,   45,   45,   50,   50,   50,   50,   50,   50,
      185,   50,   50,   50,  195,  189,   50,   50,  196,   50,
       50,   50,  359,  201,  195,  358,  202,  206,  207,   50,
       50,   50,   50,   50,   50,  210,   50,   50,   50,  195,
      213,   50,   50,  219,   50,   50,   50,   64,  201,  221,
       64,  202,  206,  207,   64,   64,  223,  224,  225,  226,
      210,   64,  227,   64,  357,  213,  234,  356,  219,  239,

      233,  354,   64,  240,  221,   64,  243,  244,  353,   64,
       64,  223,  224,  225,  226,  233,   64,  227,   64,  106,
      247,  234,  106,  250,  239,  233,  106,  106,  240,  256,
      257,  243,  244,  106,  259,  106,  260,  265,  266,  269,
      233,  270,  275,  279,  106,  247,  281,  106,  250,  282,
      284,  106,  106,  285,  256,  257,  289,  290,  106,  259,
      106,  260,  265,  266,  269,  293,  270,  275,  279,  294,
      296,  281,  297,  298,  282,  284,  299,  304,  285,  322,
      323,  289,  290,  324,  325,  330,  333,  335,  360,  361,
      293,  363,  371,  360,  294,  296,  394,  297,  298,  398,

      412,  299,  304,  413,  322,  323,  418,  352,  324,  325,
      330,  333,  335,  351,  361,  350,  363,  371,  349,  348,
      347,  394,  346,  345,  398,  412,  344,  343,  413,  342,
      341,  418,  424,  424,  424,  424,  424,  424,  424,  424,
      425,  425,  425,  425,  425,  425,  425,  425,  426,  426,
      426,  339,  426,  427,  338,  427,  428,  428,  428,  428,
      428,  428,  428,  428,  429,  336,  429,  429,  334,  429,
      430,  332,  331,  430,  430,  430,  431,  329,  431,  431,
      320,  431,  432,  318,  317,  432,  432,  432,  433,  316,
      433,  433,  315,  433,  434,  314,  313,  434,  434,  434,

      435,  312,  435,  435,  310,  435,  436,  309,  308,  436,
      436,  436,  437,  307,  437,  437,  306,  437,  438,  305,
      303,  438,  438,  438,  439,  300,  439,  439,  288,  439,
      440,  287,  286,  440,  440,  440,  441,  280,  441,  441,
      278,  441,  442,  277,  276,  442,  442,  442,  443,  273,
      443,  443,  264,  443,  444,  263,  262,  444,  444,  444,
      261,  254,  246,  245,  229,  220,  218,  217,  209,  208,
      203,  191,  186,  183,  181,  180,  178,  177,  171,  170,
      166,  165,  164,  163,  160,  159,  158,  156,  148,  142,
      140,  139,  137,  136,  130,  129,  124,  123,  122,  121,

      118,  117,  116,  114,  108,  104,  101,   94,   92,   79,
       62,   52,   48,   47,   41,   30,   19,   11,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sample.l"
/*                            * * * * * * * * * * * * * * * * * * * * * * * * *  * * * *  *
                              |          Bhagvan bharose attempt by KEVIV SINGH		 	  |
          		     		  |			 												  |
                              * * * * * * * **  ** * * ** * * * * * * * * * * * * * * * * *
*/
#line 8 "sample.l"

#include <stdio.h>
#include<string.h>
#include "y.tab.h"




#line 846 "lex.yy.c"

#define INITIAL 0
#define a_tag 1
#define font_tag 2
#define img_tag 3
#define table_tag 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 24 "sample.l"

#line 1070 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 424 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 919 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 25 "sample.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 "sample.l"
{
							printf("HTML\n");
							return HTML;
							}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "sample.l"
{
							printf("HTMLE\n");
							return HTMLE;
							}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "sample.l"
{
							printf("HEAD\n");
							return HEAD;
							}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "sample.l"
{
							printf("HEADE\n");
							return HEADE;
							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "sample.l"
{
							printf("BODY\n");
							return BODY;
							}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "sample.l"
{
							printf("BODYE\n");
							return BODYE;
							}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "sample.l"
{
							printf("TITLE\n");
							return TITLE;
							}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "sample.l"
{
							printf("TITLEE\n");
							return TITLEE;
							}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "sample.l"
{ 
											BEGIN img_tag;
											printf("IMG\n");
											return IMG;
											}
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 74 "sample.l"
{
											
														char *ss =yytext;
														int length=strlen(ss);
														char link[length+5];
														sscanf(ss, "%*[^\"]\"%[^\"]",link);
														printf("%s\n",link);
														yylval.s = malloc(2000);
														yylval.s = strdup(link);
														//BEGIN a_tag;
														return IMGSRC;

														}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "sample.l"
{
											
														char *ss =yytext;
														int length=strlen(ss);
														char link[length+5];
														sscanf(ss, "%*[^\']\'%[^\']",link);
														printf("%s\n",link);
														yylval.s = malloc(2000);
														yylval.s = strdup(link);
														//BEGIN a_tag;
														return IMGSRC;
														}
	YY_BREAK


case 13:
YY_RULE_SETUP
#line 104 "sample.l"
{
										
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\"]\"%[^\"]",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return IMGWIDTH;
															}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "sample.l"
{
										
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\']\'%[^\']",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return IMGWIDTH;
															}
	YY_BREAK


case 15:
YY_RULE_SETUP
#line 132 "sample.l"
{
										
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\"]\"%[^\"]",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return IMGHEIGHT;
															}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 144 "sample.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\']\'%[^\']",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGHEIGHT;
											}
	YY_BREAK

case 17:
YY_RULE_SETUP
#line 158 "sample.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "sample.l"
{ 
											BEGIN a_tag;
											printf("A\n");
											return A;
											}
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 172 "sample.l"
{
											
														char *ss =yytext;
														int length=strlen(ss);
														char link[length+5];
														sscanf(ss, "%*[^\"]\"%[^\"]",link);
														printf("%s\n",link);
														yylval.s = malloc(2000);
														yylval.s = strdup(link);
														//BEGIN a_tag;
														return HREF;
														}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 185 "sample.l"
{
											
														char *ss =yytext;
														int length=strlen(ss);
														char link[length+5];
														sscanf(ss, "%*[^\']\'%[^\']",link);
														printf("%s\n",link);
														yylval.s = malloc(2000);
														yylval.s = strdup(link);
														//BEGIN a_tag;
														return HREF;
														}
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 201 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\"]\"%[^\"]",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return ATITLE;
															}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 213 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\']\'%[^\']",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return ATITLE;
															}
	YY_BREAK


case 23:
YY_RULE_SETUP
#line 227 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\"]\"%[^\"]",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return ANAME;
															}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 239 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\']\'%[^\']",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															//BEGIN a_tag;
															return ANAME;
															}
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 254 "sample.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 259 "sample.l"
{
											printf("AE\n");
											return AE;
											}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 264 "sample.l"
{
															BEGIN table_tag;
															printf("TABLE\n");
															return TABLE;
															}
	YY_BREAK

case 28:
YY_RULE_SETUP
#line 273 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\"]\"%[^\"]",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															return BORDER;
															}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 284 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\']\'%[^\']",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															return BORDER;
															}
	YY_BREAK

case 30:
YY_RULE_SETUP
#line 296 "sample.l"
{
															BEGIN 0;
															}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 300 "sample.l"
{
											printf("TABLEE\n");
											return TABLEE;	
											}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 305 "sample.l"
{
											BEGIN font_tag;
											printf("FONT\n");
											return FONT;
											}
	YY_BREAK

case 33:
YY_RULE_SETUP
#line 312 "sample.l"
{
																		char *ss =yytext;
																		int length=strlen(ss);
																		char link[length+5];
																		sscanf(ss, "%*[^\"]\"%[^\"]",link);
																		printf("%s\n",link);
																		yylval.s = malloc(2000);
																		yylval.s = strdup(link);
																		return SIZE;
																		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 322 "sample.l"
{
																		char *ss =yytext;
																		int length=strlen(ss);
																		char link[length+5];
																		sscanf(ss, "%*[^\']\'%[^\']",link);
																		printf("%s\n",link);
																		yylval.s = malloc(2000);
																		yylval.s = strdup(link);
																		return SIZE;
																		}
	YY_BREAK

case 35:
YY_RULE_SETUP
#line 335 "sample.l"
{
															BEGIN 0;
															}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 340 "sample.l"
{
											printf("FONTE\n");
											return FONTE;
											}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 345 "sample.l"
{
							printf("FIGURE\n");
							return FIGURE;	
							}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 350 "sample.l"
{
							printf("FIGUREE\n");
							return FIGUREE;	
							}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 355 "sample.l"
{
							printf("FIGCAPTION\n");
							return FIGCAPTION;	
							}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 360 "sample.l"
{
							printf("FIGCAPTIONE\n");
							return FIGCAPTIONE;	
							}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 365 "sample.l"
{
							printf("CENTER\n");
							return CENTER;	
							}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 370 "sample.l"
{
							printf("CENTERE\n");
							return CENTERE;	
							}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 375 "sample.l"
{
							printf("BR\n");
							return BR;	
							}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 379 "sample.l"
{
							printf("BR\n");
							return BR;	
							}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 384 "sample.l"
{
							printf("P\n");
							return P;	
							}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 389 "sample.l"
{
							printf("PE\n");
							return PE;	
							}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 394 "sample.l"
{
							printf("H1\n");
							return H1;	
							}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 399 "sample.l"
{
							printf("H1E\n");
							return H1E;	
							}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 404 "sample.l"
{
							printf("H2\n");
							return H2;	
							}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 409 "sample.l"
{
							printf("H2E\n");
							return H2E;	
							}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 414 "sample.l"
{
							printf("H3\n");
							return H3;	
							}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 419 "sample.l"
{
							printf("H3E\n");
							return H3E;	
							}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 424 "sample.l"
{
							printf("H4\n");
							return H4;	
							}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 429 "sample.l"
{
							printf("H4E\n");
							return H4E;	
							}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 434 "sample.l"
{
							printf("UL\n");
							return UL;	
							}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 439 "sample.l"
{
							printf("ULE\n");
							return ULE;	
							}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 444 "sample.l"
{
							printf("LI\n");
							return LI;	
							}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 449 "sample.l"
{
							printf("LIE\n");
							return LIE;	
							}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 454 "sample.l"
{
							printf("OL\n");
							return OL;	
							}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 459 "sample.l"
{
							printf("OLE\n");
							return OLE;	
							}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 464 "sample.l"
{
							printf("DL\n");
							return DL;	
							}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 469 "sample.l"
{
							printf("DLE\n");
							return DLE;	
							}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 474 "sample.l"
{
							printf("DT\n");
							return DT;	
							}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 479 "sample.l"
{
							printf("DTE\n");
							return DTE;	
							}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 484 "sample.l"
{
							printf("DD\n");
							return DD;	
							}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 489 "sample.l"
{
							printf("DDE\n");
							return DDE;	
							}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 494 "sample.l"
{
							printf("DIV\n");
							return DIV;	
							}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 499 "sample.l"
{
							printf("DIVE\n");
							return DIVE;	
							}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 504 "sample.l"
{
							printf("U\n");
							return U;	
							}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 509 "sample.l"
{
							printf("UE\n");
							return UE;	
							}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 514 "sample.l"
{
							printf("B\n");
							return B;	
							}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 519 "sample.l"
{
							printf("BE\n");
							return BE;	
							}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 524 "sample.l"
{
							printf("I\n");
							return I;	
							}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 529 "sample.l"
{
							printf("IE\n");
							return IE;	
							}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 534 "sample.l"
{
							printf("EM\n");
							return EM;	
							}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 539 "sample.l"
{
							printf("EME\n");
							return EME;	
							}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 544 "sample.l"
{
							printf("TT\n");
							return TT;	
							}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 549 "sample.l"
{
							printf("TTE\n");
							return TTE;	
							}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 554 "sample.l"
{
							printf("STRONG\n");
							return STRONG;	
							}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 559 "sample.l"
{
							printf("STRONGE\n");
							return STRONGE;	
							}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 564 "sample.l"
{
							printf("SMALL\n");
							return SMALL;	
							}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 569 "sample.l"
{
							printf("SMALLE\n");
							return SMALLE;	
							}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 574 "sample.l"
{
							printf("SUB\n");
							return SUB;	
							}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 579 "sample.l"
{
							printf("SUBE\n");
							return SUBE;	
							}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 584 "sample.l"
{
							printf("SUP\n");
							return SUP;	
							}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 589 "sample.l"
{
							printf("SUPE\n");
							return SUPE;	
							}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 595 "sample.l"
{
							printf("CAPTION\n");
							return CAPTION;	
							}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 600 "sample.l"
{
							printf("CAPTIONE\n");
							return CAPTIONE;	
							}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 605 "sample.l"
{
							printf("TH\n");
							return TH;	
							}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 610 "sample.l"
{
							printf("THE\n");
							return THE;	
							}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 615 "sample.l"
{
							printf("TR\n");
							return TR;	
							}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 620 "sample.l"
{
							printf("TRE\n");
							return TRE;	
							}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 625 "sample.l"
{
							printf("TD\n");
							return TD;	
							}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 630 "sample.l"
{
							printf("TDE\n");
							return TDE;	
							}
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 635 "sample.l"
{
							printf("%s\n",yytext);
							yylval.s = malloc(2000);
							yylval.s = strdup(yytext);
							return TEXT;
							}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 642 "sample.l"
{
							printf("GREEK\n");
							yylval.s = malloc(2000);
							yylval.s = strdup(yytext);
							return GREEK;
							}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 649 "sample.l"
;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 650 "sample.l"
;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 651 "sample.l"
;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 654 "sample.l"
ECHO;
	YY_BREAK
#line 2052 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(a_tag):
case YY_STATE_EOF(font_tag):
case YY_STATE_EOF(img_tag):
case YY_STATE_EOF(table_tag):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 424 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 424 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 423);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 654 "sample.l"




int yywrap(){
return 1;
}

/*
int main(void){
yyin=fopen("sample2.html","r\n");
yylex();
}
*/








