
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[373] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
       91,   88,    1,    1,   85,   85,   88,   88,   88,   90,
       90,   18,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   22,   90,    1,    1,   85,   85,    0,    1,   85,
        0,    0,    0,    0,    0,    0,    0,   89,   15,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,    0,    0,    0,    0,   22,
        0,    0,   86,    0,   87,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,

       61,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   63,    0,
        0,    0,   35,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   59,    0,    0,    0,    0,    0,    0,    0,
        0,   19,   62,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   64,
        0,    0,   36,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   60,    0,    0,    0,    0,   33,    0,    0,
       55,    0,   51,   53,   65,    0,    0,   37,   39,   41,
       43,    0,    0,   10,   47,   49,    0,    0,    0,    0,

        0,   83,   79,    0,   81,   67,   45,    0,    0,   25,
        0,    0,    0,    0,    0,    0,    0,   56,    0,   52,
       54,   66,    0,    0,   38,   40,   42,   44,    0,    0,
       48,   50,    0,    0,    0,    0,    0,   84,   80,    0,
       82,   68,   46,    0,   34,    0,    0,   57,    0,    0,
       24,    0,    0,   10,    0,    0,   73,   75,    0,    0,
        0,    0,   25,    0,    0,    0,    0,    0,    0,    0,
       58,    0,    0,    0,    0,    0,    0,    0,   74,   76,
        0,    0,    6,    0,    0,    0,    0,   24,    4,    2,
        0,    0,   20,    0,    0,    0,    0,    0,   11,    0,

        0,    7,    0,    0,    0,    0,   26,    5,    3,    0,
        0,    0,    0,    0,    0,    0,    0,   71,    0,   20,
        8,    0,   16,    0,    0,   11,    0,    0,    0,    0,
        0,    0,   72,    0,   23,    9,    0,   31,    0,   27,
       69,   16,    0,   17,    0,    0,   12,    0,    0,   32,
        0,   28,   70,   77,    0,   17,    0,   13,   12,    0,
       21,   78,    0,    0,   13,   21,    0,    0,    0,   29,
       30,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    1,    1,
        1,    1,    1,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   15,   15,   15,   15,   15,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   15,   15,   36,   37,   38,   39,   40,
       15,   41,   42,   43,   44,   45,   46,   15,   47,   48,
        1,    1,    1,   49,    1,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   15,   15,   59,   60,   61,
       62,   63,   15,   64,   65,   66,   67,   68,   69,   15,
       70,   71,   72,    1,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[75] =
    {   0,
        1,    2,    2,    3,    4,    5,    6,    4,    4,    1,
        4,    4,    7,    5,    7,    7,    7,    7,    7,    8,
        1,    1,    7,    1,    4,    4,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    4,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    4,    4,    4
    } ;

static yyconst flex_uint16_t yy_base[385] =
    {   0,
        0,   74,   13,   67,    0,    1,   88,  117,    7,   12,
      804,  805,  185,   25,  258,    0,  129,  328,  794,  805,
       83,  805,    0,    3,    4,  171,  778,    1,    3,   10,
       65,  805,   46,   48,  101,    0,    0,  792,  109,    0,
        0,  389,  457,  791,  775,    6,  505,  805,  794,  103,
      108,  179,   69,  121,  153,  140,   74,   84,  773,  181,
      546,  180,  229,  805,  109,  133,    3,  133,  150,  260,
      772,  175,  171,  185,  805,  188,  197,  197,  227,  805,
      213,  213,  805,  771,  805,  770,  249,  249,  255,  219,
      254,  357,  769,  234,  246,  768,  283,  586,  286,  787,

      805,  266,  402,  260,  263,  766,  270,  765,  764,  763,
      295,  308,  762,  761,  760,  759,  327,  324,  805,  333,
      758,  757,  805,  372,  361,  377,  379,  756,  755,  365,
      754,  753,  805,  752,  377,  377,  387,  386,  752,  377,
      391,  805,  805,  394,  387,  391,  750,  388,  749,  748,
      747,  401,  397,  742,  736,  730,  724,  410,  408,  805,
      718,  712,  805,  421,  408,  439,  423,  709,  707,  410,
      695,  691,  805,  668,  407,  471,  663,  805,  427,  438,
      805,  662,  805,  805,  805,  455,  443,  805,  805,  805,
      805,  457,  452,  680,  805,  805,  453,  452,  659,  657,

      456,  805,  805,  458,  805,  805,  805,  657,  465,    0,
      463,  673,  464,  469,  454,  460,  462,  805,  654,  805,
      805,  805,  498,  495,  805,  805,  805,  805,  513,  510,
      805,  805,  515,  513,  653,  652,  518,  805,  805,  542,
      805,  805,  805,  651,  805,  544,  551,  805,  556,  543,
      670,  649,  574,  593,  549,  548,  805,  805,  557,  560,
      587,  567,    0,  549,  547,  502,  553,  494,  560,  569,
      805,  592,  581,  492,  489,  484,  588,  587,  805,  805,
      595,  597,  805,  591,  590,  592,  602,  455,  805,  805,
      431,  601,  442,  415,  397,  386,  342,  347,  344,  341,

      321,  805,  596,  596,  598,  609,  805,  805,  805,  316,
      608,  315,  313,  608,  312,  616,  311,  805,  310,  314,
      805,  303,  300,  291,  281,  267,  262,  238,  624,  218,
      622,  206,  805,  171,  805,  805,  166,  805,  631,  805,
      805,  177,  174,  162,  155,  122,  121,  113,   94,  805,
      632,  805,  805,  805,  629,  111,  108,   86,   56,   53,
       50,  805,  631,  633,   49,   44,  634,   22,    9,  805,
      805,  805,  695,  703,  710,  714,  721,  727,  732,  738,
      744,  750,  756,  762
    } ;

static yyconst flex_int16_t yy_def[385] =
    {   0,
      373,  373,  374,  374,  374,  374,  374,  374,  374,  374,
      372,  372,  375,  372,  375,   15,  376,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,   15,   15,   15,   15,  372,  372,   15,
       15,  376,  376,  372,  377,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  377,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  378,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  378,  372,  379,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  380,  372,  372,  379,  372,  372,

      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  380,  372,  381,  372,  372,  382,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  381,  372,  383,  382,  372,  384,  372,  372,
      372,  372,  372,  372,  372,  372,  383,  372,  372,  384,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,    0,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372
    } ;

static yyconst flex_uint16_t yy_nxt[880] =
    {   0,
       12,   13,   14,   13,  372,   12,   16,   16,   16,   17,
       31,   16,  372,   12,  372,   31,   21,  372,   46,   12,
       12,   18,   16,   12,   19,   16,   39,   39,   39,   48,
       32,   76,  371,  135,   33,   32,   22,   68,   69,   33,
       67,   25,   25,   77,   78,  370,   23,  366,   16,   34,
       35,   34,  365,  366,   76,   24,  135,   33,  361,  359,
       68,   69,   33,   67,   25,   25,   77,   78,   79,   23,
       21,   16,   16,   16,   12,   13,   14,   13,   24,   12,
       16,   16,   16,   17,   82,   16,   63,   12,   80,  365,
       22,   26,   81,   12,   12,   18,   16,   12,   19,   16,

       23,   27,   34,   35,   34,  110,   64,   82,  121,   24,
       39,   39,   39,  358,  356,   81,   65,  362,  361,  122,
       26,   28,   16,   23,  359,   66,  101,  347,  110,   29,
       27,  121,   24,   30,  104,   43,   43,   43,  105,   65,
       43,  102,  122,  103,   28,   16,   16,   16,   66,   67,
       28,   43,   29,   44,   43,  111,   30,  104,   29,  112,
      358,  105,   30,  119,  102,  356,  103,   68,  113,  114,
      115,  116,   67,   28,   70,  136,  120,   43,  111,  344,
      342,   29,  112,  117,   71,   30,   34,   35,   34,  354,
       68,   37,   37,   37,  353,  118,   37,  137,  136,  120,

       43,   43,   43,  133,   72,   76,  117,   37,  106,   38,
       37,   77,   73,  107,  108,  134,   74,  124,  118,   78,
      137,  109,  138,  125,  126,  139,  140,   72,   76,  352,
       79,  106,   63,   37,   77,   73,  107,  108,  134,   74,
      124,  350,   78,  348,  109,  138,  125,  126,  139,  140,
       80,   82,   64,  141,   81,  151,   37,   37,   37,   40,
       41,   40,   65,   70,   37,   37,   37,  347,  161,   37,
      326,   66,  143,   71,   82,  145,  141,   81,  151,  146,
       37,  162,   38,   37,  147,   65,  345,  144,  152,  148,
      149,  161,  153,   72,   66,  175,  344,  150,  145,  179,

      180,   73,  146,  342,  162,   74,   37,  147,  323,  173,
      144,  152,  148,  149,  182,  153,   72,  320,  175,  164,
      150,  174,  179,  180,   73,  165,  166,  186,   74,   37,
       37,   37,   45,  341,  340,  338,  336,  182,  335,  333,
       46,   47,  164,  328,  174,  187,  327,  326,  165,  166,
      186,   48,  299,  192,   49,   50,   51,   52,   53,   54,
      193,   55,   56,   57,  325,  194,   58,   59,  187,   60,
       61,   62,  154,  155,  156,  157,  192,   49,   50,   51,
       52,   53,   54,  193,   55,   56,   57,  158,  194,   58,
       59,  324,   60,   61,   62,   43,   43,   43,  197,  159,

       43,  198,  323,  176,  199,  176,  201,  204,  208,   83,
      158,   43,  209,   44,   43,  177,  200,  210,  211,  213,
      214,  197,  159,  215,  198,  178,  216,  199,  217,  201,
      204,  208,  219,  223,  224,  209,  229,   43,  321,  200,
      210,  211,  213,  214,  230,  320,  215,  233,  234,  216,
      237,  217,  240,  244,  318,  219,  223,  224,  288,  229,
       43,   43,   43,   43,   43,   43,  235,  230,   43,  246,
      233,  234,  176,  237,  176,  240,  244,   83,  236,   43,
      247,   44,   43,  249,  177,  251,  252,  253,  255,  235,
      256,  259,  246,  260,  178,  262,  264,  266,  250,  267,

      268,  236,  269,  247,  270,   43,  249,  309,  251,  252,
      253,  255,  308,  256,  259,  307,  260,  302,  262,  264,
      266,  250,  267,  268,  300,  269,  272,  270,   43,   43,
       43,   86,   87,   88,   89,   90,   91,  274,   92,   93,
       94,  273,  275,   95,   96,  276,   97,   98,   99,  272,
      277,  278,  299,  281,   86,   87,   88,   89,   90,   91,
      274,   92,   93,   94,  273,  275,   95,   96,  276,   97,
       98,   99,  127,  277,  278,  128,  281,  282,  284,  129,
      130,  285,  286,  287,  291,  292,  131,  293,  132,  296,
      294,  297,  295,  301,  303,  127,  254,  290,  128,  304,

      282,  284,  129,  130,  285,  286,  287,  291,  292,  131,
      293,  132,  167,  294,  297,  168,  301,  303,  305,  169,
      170,  306,  304,  310,  311,  312,  171,  313,  172,  314,
      315,  316,  317,  319,  329,  167,  330,  331,  168,  332,
      334,  305,  169,  170,  306,  337,  310,  311,  312,  171,
      313,  172,  314,  315,  316,  317,  319,  329,  339,  330,
      331,  349,  332,  334,  351,  355,  363,  364,  337,  367,
      368,  369,  289,  288,  283,  280,  279,  271,  265,  261,
      258,  339,  257,  254,  349,  248,  245,  351,  355,  363,
      364,  243,  367,  368,  369,   15,   15,   15,   15,   15,

       15,   15,   15,   20,   20,   20,   20,   20,   20,   20,
       20,   36,   36,   36,  242,   36,   36,   42,  241,   42,
       42,   84,   84,   84,   84,   84,   84,   84,   84,  263,
      239,  263,  238,  263,  298,  232,  298,  298,  298,  298,
      322,  231,  322,  322,  322,  322,  343,  228,  343,  343,
      343,  343,  346,  227,  346,  346,  346,  346,  357,  226,
      357,  357,  357,  357,  360,  225,  360,  360,  360,  360,
      222,  221,  220,  218,  212,  207,  206,  205,  203,  202,
      196,  195,  191,  190,  189,  188,  185,  184,  183,  181,
      100,  163,  160,  142,   85,   75,  123,  100,   85,   42,

       36,   75,   36,  372,   11,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static yyconst flex_int16_t yy_chk[880] =
    {   0,
        1,    1,    1,    1,    0,    1,    1,    1,    1,    1,
        9,    1,    0,    1,    0,   10,    3,    0,   46,    1,
        1,    1,    1,    1,    1,    1,   14,   14,   14,   46,
        9,   28,  369,   67,    9,   10,    3,   24,   25,   10,
       23,    5,    6,   29,   30,  368,    3,  366,    1,   34,
       34,   34,  365,  361,   28,    3,   67,    9,  360,  359,
       24,   25,   10,   23,    5,    6,   29,   30,   31,    3,
        4,    1,    1,    1,    2,    2,    2,    2,    3,    2,
        2,    2,    2,    2,   33,    2,   21,    2,   31,  358,
        4,    7,   31,    2,    2,    2,    2,    2,    2,    2,

        4,    7,   35,   35,   35,   53,   21,   33,   57,    4,
       39,   39,   39,  357,  356,   31,   21,  349,  348,   58,
        8,    7,    2,    4,  347,   21,   50,  346,   53,    7,
        8,   57,    4,    7,   51,   17,   17,   17,   51,   21,
       17,   50,   58,   50,    7,    2,    2,    2,   21,   65,
        8,   17,    7,   17,   17,   54,    7,   51,    8,   54,
      345,   51,    8,   56,   50,  344,   50,   66,   55,   55,
       55,   55,   65,    8,   26,   68,   56,   17,   54,  343,
      342,    8,   54,   55,   26,    8,   13,   13,   13,  337,
       66,   13,   13,   13,  334,   55,   13,   69,   68,   56,

       17,   17,   17,   62,   26,   72,   55,   13,   52,   13,
       13,   73,   26,   52,   52,   62,   26,   60,   55,   74,
       69,   52,   76,   60,   60,   77,   78,   26,   72,  332,
       79,   52,   63,   13,   73,   26,   52,   52,   62,   26,
       60,  330,   74,  328,   52,   76,   60,   60,   77,   78,
       79,   81,   63,   82,   79,   90,   13,   13,   13,   15,
       15,   15,   63,   70,   15,   15,   15,  327,   94,   15,
      326,   63,   87,   70,   81,   88,   82,   79,   90,   88,
       15,   95,   15,   15,   89,   63,  325,   87,   91,   89,
       89,   94,   91,   70,   63,  102,  324,   89,   88,  104,

      105,   70,   88,  323,   95,   70,   15,   89,  322,   99,
       87,   91,   89,   89,  107,   91,   70,  320,  102,   97,
       89,   99,  104,  105,   70,   97,   97,  111,   70,   15,
       15,   15,   18,  319,  317,  315,  313,  107,  312,  310,
       18,   18,   97,  301,   99,  112,  300,  299,   97,   97,
      111,   18,  298,  117,   18,   18,   18,   18,   18,   18,
      118,   18,   18,   18,  297,  120,   18,   18,  112,   18,
       18,   18,   92,   92,   92,   92,  117,   18,   18,   18,
       18,   18,   18,  118,   18,   18,   18,   92,  120,   18,
       18,  296,   18,   18,   18,   42,   42,   42,  124,   92,

       42,  125,  295,  103,  126,  103,  127,  130,  135,   42,
       92,   42,  136,   42,   42,  103,  126,  137,  138,  140,
      141,  124,   92,  144,  125,  103,  145,  126,  146,  127,
      130,  135,  148,  152,  153,  136,  158,   42,  294,  126,
      137,  138,  140,  141,  159,  293,  144,  164,  165,  145,
      167,  146,  170,  175,  291,  148,  152,  153,  288,  158,
       42,   42,   42,   43,   43,   43,  166,  159,   43,  179,
      164,  165,  176,  167,  176,  170,  175,   43,  166,   43,
      180,   43,   43,  186,  176,  187,  192,  193,  197,  166,
      198,  201,  179,  204,  176,  209,  211,  213,  186,  214,

      215,  166,  216,  180,  217,   43,  186,  276,  187,  192,
      193,  197,  275,  198,  201,  274,  204,  268,  209,  211,
      213,  186,  214,  215,  266,  216,  223,  217,   43,   43,
       43,   47,   47,   47,   47,   47,   47,  224,   47,   47,
       47,  223,  229,   47,   47,  230,   47,   47,   47,  223,
      233,  234,  265,  237,   47,   47,   47,   47,   47,   47,
      224,   47,   47,   47,  223,  229,   47,   47,  230,   47,
       47,   47,   61,  233,  234,   61,  237,  240,  246,   61,
       61,  247,  249,  250,  255,  256,   61,  259,   61,  262,
      260,  264,  261,  267,  269,   61,  254,  253,   61,  270,

      240,  246,   61,   61,  247,  249,  250,  255,  256,   61,
      259,   61,   98,  260,  264,   98,  267,  269,  272,   98,
       98,  273,  270,  277,  278,  281,   98,  282,   98,  284,
      285,  286,  287,  292,  303,   98,  304,  305,   98,  306,
      311,  272,   98,   98,  273,  314,  277,  278,  281,   98,
      282,   98,  284,  285,  286,  287,  292,  303,  316,  304,
      305,  329,  306,  311,  331,  339,  351,  355,  314,  363,
      364,  367,  252,  251,  244,  236,  235,  219,  212,  208,
      200,  316,  199,  194,  329,  182,  177,  331,  339,  351,
      355,  174,  363,  364,  367,  373,  373,  373,  373,  373,

      373,  373,  373,  374,  374,  374,  374,  374,  374,  374,
      374,  375,  375,  375,  172,  375,  375,  376,  171,  376,
      376,  377,  377,  377,  377,  377,  377,  377,  377,  378,
      169,  378,  168,  378,  379,  162,  379,  379,  379,  379,
      380,  161,  380,  380,  380,  380,  381,  157,  381,  381,
      381,  381,  382,  156,  382,  382,  382,  382,  383,  155,
      383,  383,  383,  383,  384,  154,  384,  384,  384,  384,
      151,  150,  149,  147,  139,  134,  132,  131,  129,  128,
      122,  121,  116,  115,  114,  113,  110,  109,  108,  106,
      100,   96,   93,   86,   84,   71,   59,   49,   45,   44,

       38,   27,   19,   11,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      372,  372,  372,  372,  372,  372,  372,  372,  372
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sample.l"
/*                            * * * * * * * * * * * * * * * * * * * * * * * * *  * * * *  *
                              |          Bhagvan bharose attempt by KEVIV SINGH		 	  |
          		     		  |			 												  |
                              * * * * * * * **  ** * * ** * * * * * * * * * * * * * * * * *
*/
#line 8 "sample.l"

#include <stdio.h>
#include<string.h>
#include "y.tab.h"




#line 798 "lex.yy.c"

#define INITIAL 0
#define a_tag 1
#define font_tag 2
#define img_tag 3
#define table_tag 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 23 "sample.l"

#line 1022 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 373 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 805 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 24 "sample.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "sample.l"
{
							printf("HTML\n");
							return HTML;
							}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "sample.l"
{
							printf("HTMLE\n");
							return HTMLE;
							}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "sample.l"
{
							printf("HEAD\n");
							return HEAD;
							}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "sample.l"
{
							printf("HEADE\n");
							return HEADE;
							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "sample.l"
{
							printf("BODY\n");
							return BODY;
							}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "sample.l"
{
							printf("BODYE\n");
							return BODYE;
							}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "sample.l"
{
							printf("TITLE\n");
							return TITLE;
							}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "sample.l"
{
							printf("TITLEE\n");
							return TITLEE;
							}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 65 "sample.l"
{ 
											BEGIN img_tag;
											printf("IMG\n");
											return IMG;
											}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "sample.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGSRC;
											}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "sample.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGWIDTH;
											}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 97 "sample.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return IMGHEIGHT;
											}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "sample.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "sample.l"
{ 
											BEGIN a_tag;
											printf("A\n");
											return A;
											}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "sample.l"
{
											
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return HREF;
											}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "sample.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											//BEGIN a_tag;
											return ATITLE;
											}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "sample.l"
{
											BEGIN 0;
											}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 154 "sample.l"
{
											printf("AE\n");
											return AE;
											}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 159 "sample.l"
{
															BEGIN table_tag;
															printf("TABLE\n");
															return TABLE;
															}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 165 "sample.l"
{
															char *ss =yytext;
															int length=strlen(ss);
															char link[length+5];
															sscanf(ss, "%*[^\"]\"%[^\"]",link);
															printf("%s\n",link);
															yylval.s = malloc(2000);
															yylval.s = strdup(link);
															return BORDER;
															}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 176 "sample.l"
{
															BEGIN 0;
															}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 180 "sample.l"
{
											printf("TABLEE\n");
											return TABLEE;	
											}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 185 "sample.l"
{
											BEGIN font_tag;
											printf("FONT\n");
											return FONT;
											}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 191 "sample.l"
{
											char *ss =yytext;
											int length=strlen(ss);
											char link[length+5];
											sscanf(ss, "%*[^\"]\"%[^\"]",link);
											printf("%s\n",link);
											yylval.s = malloc(2000);
											yylval.s = strdup(link);
											BEGIN 0;
											return SIZE;
									
											}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 205 "sample.l"
{
											printf("FONTE\n");
											return FONTE;
											}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 210 "sample.l"
{
							printf("FIGURE\n");
							return FIGURE;	
							}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 215 "sample.l"
{
							printf("FIGUREE\n");
							return FIGUREE;	
							}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 220 "sample.l"
{
							printf("FIGCAPTION\n");
							return FIGCAPTION;	
							}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 225 "sample.l"
{
							printf("FIGCAPTIONE\n");
							return FIGCAPTIONE;	
							}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 230 "sample.l"
{
							printf("CENTER\n");
							return CENTER;	
							}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 235 "sample.l"
{
							printf("CENTERE\n");
							return CENTERE;	
							}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 240 "sample.l"
{
							printf("BR\n");
							return BR;	
							}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 244 "sample.l"
{
							printf("BRS\n");
							return BRS;	
							}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 249 "sample.l"
{
							printf("P\n");
							return P;	
							}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 254 "sample.l"
{
							printf("PE\n");
							return PE;	
							}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 259 "sample.l"
{
							printf("H1\n");
							return H1;	
							}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 264 "sample.l"
{
							printf("H1E\n");
							return H1E;	
							}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 269 "sample.l"
{
							printf("H2\n");
							return H2;	
							}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 274 "sample.l"
{
							printf("H2E\n");
							return H2E;	
							}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 279 "sample.l"
{
							printf("H3\n");
							return H3;	
							}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 284 "sample.l"
{
							printf("H3E\n");
							return H3E;	
							}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 289 "sample.l"
{
							printf("H4\n");
							return H4;	
							}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 294 "sample.l"
{
							printf("H4E\n");
							return H4E;	
							}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 299 "sample.l"
{
							printf("UL\n");
							return UL;	
							}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 304 "sample.l"
{
							printf("ULE\n");
							return ULE;	
							}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 309 "sample.l"
{
							printf("LI\n");
							return LI;	
							}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 314 "sample.l"
{
							printf("LIE\n");
							return LIE;	
							}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 319 "sample.l"
{
							printf("OL\n");
							return OL;	
							}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 324 "sample.l"
{
							printf("OLE\n");
							return OLE;	
							}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 329 "sample.l"
{
							printf("DL\n");
							return DL;	
							}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 334 "sample.l"
{
							printf("DLE\n");
							return DLE;	
							}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 339 "sample.l"
{
							printf("DT\n");
							return DT;	
							}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 344 "sample.l"
{
							printf("DTE\n");
							return DTE;	
							}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 349 "sample.l"
{
							printf("DD\n");
							return DD;	
							}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 354 "sample.l"
{
							printf("DDE\n");
							return DDE;	
							}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 359 "sample.l"
{
							printf("DIV\n");
							return DIV;	
							}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 364 "sample.l"
{
							printf("DIVE\n");
							return DIVE;	
							}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 369 "sample.l"
{
							printf("U\n");
							return U;	
							}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 374 "sample.l"
{
							printf("UE\n");
							return UE;	
							}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 379 "sample.l"
{
							printf("B\n");
							return B;	
							}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 384 "sample.l"
{
							printf("BE\n");
							return BE;	
							}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 389 "sample.l"
{
							printf("I\n");
							return I;	
							}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 394 "sample.l"
{
							printf("IE\n");
							return IE;	
							}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 399 "sample.l"
{
							printf("EM\n");
							return EM;	
							}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 404 "sample.l"
{
							printf("EME\n");
							return EME;	
							}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 409 "sample.l"
{
							printf("TT\n");
							return TT;	
							}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 414 "sample.l"
{
							printf("TTE\n");
							return TTE;	
							}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 419 "sample.l"
{
							printf("STRONG\n");
							return STRONG;	
							}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 424 "sample.l"
{
							printf("STRONGE\n");
							return STRONGE;	
							}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 429 "sample.l"
{
							printf("SMALL\n");
							return SMALL;	
							}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 434 "sample.l"
{
							printf("SMALLE\n");
							return SMALLE;	
							}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 439 "sample.l"
{
							printf("SUB\n");
							return SUB;	
							}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 444 "sample.l"
{
							printf("SUBE\n");
							return SUBE;	
							}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 449 "sample.l"
{
							printf("SUP\n");
							return SUP;	
							}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 454 "sample.l"
{
							printf("SUPE\n");
							return SUPE;	
							}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 460 "sample.l"
{
							printf("CAPTION\n");
							return CAPTION;	
							}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 465 "sample.l"
{
							printf("CAPTIONE\n");
							return CAPTIONE;	
							}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 470 "sample.l"
{
							printf("TH\n");
							return TH;	
							}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 475 "sample.l"
{
							printf("THE\n");
							return THE;	
							}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 480 "sample.l"
{
							printf("TR\n");
							return TR;	
							}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 485 "sample.l"
{
							printf("TRE\n");
							return TRE;	
							}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 490 "sample.l"
{
							printf("TD\n");
							return TD;	
							}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 495 "sample.l"
{
							printf("TDE\n");
							return TDE;	
							}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 500 "sample.l"
{
							printf("%s\n",yytext);
							yylval.s = malloc(2000);
							yylval.s = strdup(yytext);
							return TEXT;
							}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 507 "sample.l"
{
							printf("GREEK\n");
							yylval.s = malloc(2000);
							yylval.s = strdup(yytext);
							return GREEK;
							}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 514 "sample.l"
;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 515 "sample.l"
;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 516 "sample.l"
;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 519 "sample.l"
ECHO;
	YY_BREAK
#line 1845 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(a_tag):
case YY_STATE_EOF(font_tag):
case YY_STATE_EOF(img_tag):
case YY_STATE_EOF(table_tag):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 373 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 373 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 372);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 519 "sample.l"




int yywrap(){
return 1;
}

/*
int main(void){
yyin=fopen("sample2.html","r\n");
yylex();
}
*/








